Addition

In [1]:
import numpy as np

x=np.array([2,3,4,5])
y=np.array([6,7,8,9])
add=np.add(x,y)
print(add)


[ 8 10 12 14]


Subtraction

In [2]:
import numpy as np

x=np.array([2,3,4,5])
y=np.array([6,7,8,9])
sub=np.subtract(x,y)
print(sub)


[-4 -4 -4 -4]


Multiplication

In [3]:
import numpy as np

x=np.array([2,3,4,5])
y=np.array([6,7,8,9])
mul=np.multiply(x,y)
print(mul)


[12 21 32 45]


Division

In [6]:
import numpy as np

x=np.array([12,21,40,45])
y=np.array([6,7,8,9])
div=np.divide(x,y)
print(div)


[2. 3. 5. 5.]


Power

In [8]:
import numpy as np

x=np.array([2,4,5,10])
y=np.array([3,2,2,4])
pow=np.power(x,y)
print(pow)


[    8    16    25 10000]


Remainder

In [13]:
import numpy as np

x=np.array([10,21,42,41])
y=np.array([6,7,8,9])
rem=np.mod(x,y)
print(rem)


[4 0 2 5]


Remainder

In [14]:
import numpy as np

x=np.array([10,21,42,41])
y=np.array([6,7,8,9])
rem=np.remainder(x,y)
print(rem)


[4 0 2 5]


Quotient and Mod

In [15]:
import numpy as np

x=np.array([10,21,42,41])
y=np.array([6,7,8,9])
Quotient_rem=np.divmod(x,y)
print(Quotient_rem)


(array([1, 3, 5, 4]), array([4, 0, 2, 5]))


Absolute

In [17]:
import numpy as np

x=np.array([-10,-21,-42,-41])
print(np.absolute(x))


[10 21 42 41]
