Trigonometric Functions

In [1]:
import numpy as np

print(np.sin(np.pi/2))

1.0


Find sine values for all of the values in array:

In [10]:
import numpy as np

arr=np.array([np.pi/4,np.pi/2,np.pi/3,np.pi/5])
print(np.sin(arr))

[0.70710678 1.         0.8660254  0.58778525]


Convert Degrees Into Radians

In [11]:
import numpy as np

arr=np.array([90,180,270,360])
print(np.deg2rad(arr))

[1.57079633 3.14159265 4.71238898 6.28318531]


Radians to Degrees


In [13]:
import numpy as np

arr=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
print(np.rad2deg(arr))

[ 90. 180. 270. 360.]
