Create Sets in NumPy

In [2]:
import numpy as np

arr=np.array([2,1,1,1,2,2,3,4,5,5,7,8,7,3])
print(np.unique(arr))

[1 2 3 4 5 7 8]


Finding Union

In [3]:
import  numpy as np

arr1=np.array([1,2,4,5,3,4])
arr2=np.array([2,5,6,8,9,11])

print(np.union1d(arr1,arr2))

[ 1  2  3  4  5  6  8  9 11]


Finding Intersection

In [4]:
import  numpy as np

arr1=np.array([1,2,4,5,3,4])
arr2=np.array([2,5,6,8,9,11])

print(np.intersect1d(arr1,arr2))

[2 5]


Finding Difference

In [7]:
import  numpy as np

arr1=np.array([1,2,4,5,3,4])
arr2=np.array([2,5,6,8,9,11])

print(np.setdiff1d(arr1,arr2))

[1 3 4]


Finding Symmetric Difference

In [8]:
import  numpy as np

arr1=np.array([1,2,4,5,3,4])
arr2=np.array([2,5,6,8,9,11])

print(np.setxor1d(arr1,arr2))

[ 1  3  4  6  8  9 11]
