Truncation

In [1]:
import numpy as np

arr=np.trunc([3.22,4.3343,5.10])
print(arr)

[3. 4. 5.]


Fix

In [2]:
import numpy as np

arr=np.fix([3.22,4.3343,5.10])
print(arr)

[3. 4. 5.]


Rounding

In [4]:
import numpy as np

arr=np.around([3.27894,4.34564,5.14564],2)
print(arr)

[3.28 4.35 5.15]


Floor

In [2]:
import numpy as np

arr=np.array([-2.342,-3.6423,2.342,3.6423,4.99])
print(np.floor(arr))

[-3. -4.  2.  3.  4.]


Ceil

In [4]:
import numpy as np

arr=np.ceil([-3.423,-3.6756,3.545])
print(arr)

[-3. -3.  4.]
